name: Docker Build and Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: build local container
        uses: docker/build-push-action@v4
        with:
          tags: localbuild/javaapp:latest
          push: false
          load: true
      
      # - name: Scan image
      #   uses: anchore/scan-action@v6
      #   with:
      #     image: "localbuild/javaapp:latest"
      #     output-format: cyclonedx-xml
      #     output-file: grype-scan-report.xml
      #     fail-build: false
      #     severity-cutoff: critical

      # - name: Upload vulnerability report
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: grype-scan-report
      #     path: grype-scan-report.xml

      - name: Scan image
        uses: anchore/scan-action@v6
        with:
          image: "localbuild/javaapp:latest"
          output-format: sarif
          output-file: grype-scan-report.sarif
          fail-build: false
          severity-cutoff: critical

      - name: Upload vulnerability report
        uses: actions/upload-artifact@v4
        with:
          name: grype-scan-report
          path: grype-scan-report.sarifd