name: Docker Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: build local container
        uses: docker/build-push-action@v4
        with:
          tags: localbuild/javaapp:latest
          push: false
          load: true
      
      - name: Scan image and generate HTML report
        run: |
            sudo curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b . v0.87.0
        
            ./grype localbuild/javaapp:latest \
              -o template \
              --template ./templates/html.tmpl \
              --file grype-report.html \
              --fail-on critical || true
        continue-on-error: true
        
      - name: Upload HTML scan report
        uses: actions/upload-artifact@v4
        with:
          name: grype-html-report
          path: grype-report.html
    